[MI-3230]: Developed a modal which opens on click of view button in config table
Brightscout/mattermost-plugin-welcomebot pull request #6
Opened 2023-07-03 13:24 UTC by Kshitij-Katiyar

## Summary

Developed a modal to open on click of view button in existing config table to receive and show the attachment  message

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +function EditActionsModal(props: Props) {
destructure the objects here only

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +    };
```suggestion
    };
    
```

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +                            <div className='dropdown'>
fix the indentations everywhere

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +                                <Form.Select aria-label='Default select example'>
why this aria-label='Default select example' ?

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +                                </Form.Select></div>
fix identations

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +export default EditActionsModal;
Add EOF

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/styles.css
> +}
same

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +export default ViewActionsModal;
eof

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +                                placeholder='Enter the display name of your action'
remove your in every place holder like here Enter the display name of the action.

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +                                placeholder='This is a example attachment message'
change this

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/tables/existingConfigTable.tsx
> +    const [vis, setVis] = useState(false);
bad naming conventions

2023-07-14 12:04 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/tables/existingConfigTable.tsx
> +                                            >{'Edit'}</Button>
identaions

2023-08-10 11:24 UTC, raghavaggarwal2308 requested changes

2023-08-10 11:24 UTC, raghavaggarwal2308 commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +import Form from 'react-bootstrap/Form';
Fix import order

2023-08-10 11:24 UTC, raghavaggarwal2308 commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +    setVis: React.Dispatch<React.SetStateAction<boolean>>;
```suggestion
    setVisible: React.Dispatch<React.SetStateAction<boolean>>;
```

2023-08-10 11:24 UTC, raghavaggarwal2308 commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +                                <td>{'Welcome to your new team mate !'}</td>
```suggestion
                                <td>{'Welcome to your new team mate!'}</td>
```

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +interface Props {
use `types`

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +function EditActionsModal({visible, setVis}: Props) {
make it an arrow function

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +export default EditActionsModal;
+1

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/styles.css
> +}
+1

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +function ViewActionsModal(props: Props) {
same as above fix for all such places

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +        <>
this is not needed as there is a single parent wrapper.

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +        <>
this is not needed as there is a single parent wrapper.

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/tables/existingConfigTable.tsx
> +                                                onClick={handleViews}
change the name of `handleViews` to support this button `Edit`

2023-08-10 13:59 UTC, avas27JTG commented on webapp/src/containers/components/tables/existingConfigTable.tsx
> +                                            </Button>
same

2023-08-11 14:23 UTC, raghavaggarwal2308 requested changes

2023-08-11 14:23 UTC, raghavaggarwal2308 commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +    setVis: React.Dispatch<React.SetStateAction<boolean>>;
Why have you marked this as resolved if it is not fixed?

2023-08-17 06:12 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/editActionsModal.tsx
> +    setVis: React.Dispatch<React.SetStateAction<boolean>>;
fixed

2023-08-23 16:02 UTC, avas27JTG commented on webapp/src/containers/components/modals/styles.css
> +    padding-top: 10%;
why `%ge` and not `px`?

2023-08-23 16:02 UTC, avas27JTG commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +}
use `types`

2023-08-23 16:02 UTC, avas27JTG commented on webapp/src/containers/components/modals/viewActionsModal.tsx
> +    return (
```suggestion

    return (
```

2023-08-24 08:31 UTC, Kshitij-Katiyar commented on webapp/src/containers/components/modals/styles.css
> +    padding-top: 10%;
using % to keep the design responsive

2023-08-24 15:11 UTC, raghavaggarwal2308 approved these changes

2023-08-29 07:37 UTC, avas27JTG commented on webapp/src/containers/components/modals/styles.css
> +    padding-top: 10%;
It works fine here but % itself doesn't make the design responsive you can learn more about it to use it wisely.

2023-08-29 07:37 UTC, avas27JTG approved these changes

2023-09-01 06:12 UTC, merged